# Generated by Django 4.2.7 on 2023-11-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_author_alter_note_description_alter_note_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Author_note',
        ),
    ]
