# Generated by Django 4.2.7 on 2023-12-01 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noteapp', '0004_rename_author_author_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_note',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='author_note',
            field=models.ManyToManyField(to='noteapp.author_note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='noteapp.tag'),
        ),
    ]
