# Generated by Django 4.2.7 on 2023-12-01 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_author_note_user_note_author_note_alter_note_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='author_note',
            new_name='authornote',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='nametag',
        ),
        migrations.RemoveField(
            model_name='note',
            name='name',
        ),
    ]
