# Generated by Django 4.2.7 on 2023-12-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0007_remove_tag_tag_of_username_tag_tag_of_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag of username',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'description'), name='tag of username'),
        ),
    ]
