# Generated by Django 4.2.7 on 2023-12-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0009_remove_tag_tag_of_username_rename_nametag_tag_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='authornote',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Author_note',
        ),
    ]
