# Generated by Django 4.2.7 on 2023-12-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noteapp', '0010_remove_note_authornote_remove_tag_tag_tag_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Author_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('born_date', models.DateTimeField(auto_now_add=True)),
                ('born_location', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='authornote',
            field=models.ManyToManyField(to='noteapp.author_note'),
        ),
    ]
